server:
  port: 8887
github:
  client:
    id: 6f3ce7d3418c7adc7bad
    secret: 7dcbebb072fc1806bfe4c4ab454f36a616cb27f7
  redirect:
    uri: http://localhost:8887/callback
spring:
  datasource:
    url: jdbc:h2:~/community
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver